config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/software'

  get 'static_pages/music'

  get 'resume/download'

  root 'static_pages#home'
  match '/static_pages/home', to: 'static_pages#home', via: 'get'
  match '/software',    to: 'static_pages#software',    via: 'get'
  match '/music',   to: 'static_pages#music',   via: 'get'
  match '/works', to: 'static_pages#works', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def download
    send_file(
      "#{Rails.root}/app/assets/other/Roberts-Resume.pdf",
      filename: "Roberts-Resume.pdf",
      type: "application/pdf"
    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def software
  end

  def music
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "David Roberts"
    if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
        <li><%= link_to "home",   root_path %></li>
        <li><%= link_to "software",    software_path %></li>
        <li><%= link_to "music", music_path %></li>
        <li><%= link_to "works", works_path %></li>
        <li><%= link_to "resume", resume_download_url %></li>
    </ul>
  </nav>
</footer>

<!-- <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to "home",   root_path %></li>
      <li><%= link_to "software",    software_path %></li>
      <li><%= link_to "music", music_path %></li>
      <li><%= link_to "works", works_path %></li>
      <li><a href="/resume">resume</a></li>
    </ul>
  </div>
</nav> -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">David Roberts</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "home",   root_path %></li>
        <li><%= link_to "software",    software_path %></li>
        <li><%= link_to "music", music_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Twitter", "http://www.twitter.com/smoip" %></li>
        <li><%= link_to "Github", "http://www.github.com/smoip" %></li>
        <li><%= link_to "E-mail", "mailto:drsmoip@gmail.com" %></li>
        <li><%= link_to "LinkedIn", "https://www.linkedin.com/pub/david-roberts/1b/24b/259" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>

    <div class="hero-unit">
      <div class="container">
        <div class="row-fluid">
          <div class="span12">
            <div class="inner-box">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
              <% end %>
              <%= yield %>
              <%= debug(params) if Rails.env.development? %>
            </div>
          </div>
        </div>
      </div>
    </div>

  <%= render 'layouts/footer' %>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
  <h1>About Me</h1>
  <%= image_tag("david_face.jpg", alt: "David Roberts", class: "img-float-left") %>
  <p>I’m a composer, software engineer, brewer, and sound designer living in Chicago.<p>
  <p>I believe strongly that the best ideas start from a simple, functional base and well-considered
  details, and I strive to bring this perspective to all of my work, be it a string quartet, an
  algorithm for destroying sound, or a crisp session IPA.</p>

  <p>
    I have my fingers in many pots and can be found
    <%= link_to "putting on concerts", "http://www.secondcycleensemble.com" %>,
    <%= link_to "ranting about art music", "https://musicalinvective.wordpress.com/" %>,
    <%= link_to "teaching people to make beer", "http://www.brewcamp.com" %>, or running on the lakefront.
  </p>
  <p>Boring professional credentials can be found on my <%= link_to 'resume', resume_download_url %>.</p>

app/views/static_pages/music.html.erb
<% provide(:title, 'Music') %>
  <h1>Music</h1>
  <div class="player-float-right">
    <iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/94998231&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe>
  </div>
  <p>Music has and always will be a driving force in my life, and my education
    in composition has lead me to engage with it in a number of ways: writing music (of course),
    but also writing about music, organizing concerts and events, recording and
    mastering, and designing crazy electronic instruments (which dovetails
    nicely with my work in software).</p>

  <p>I have written music for all kinds of ensembles and instrumentations (everything
    from serious concert music to pop tunes and video game arrangements), but I have a soft
    spot for string-driven chamber music and focus mainly on pieces involving electronics in some capacity.</p>
  <p>Below are a few of my current projects.</p>

  <h2>Selected Projects</h2>
  <ul>
    <li>
      <h3><%= link_to "Second/Cycle", "http://www.secondcycleensemble.com" %></h3>
      <p>Second/Cyle is a Chicago-based new music ensemble I co-direct with the beautiful
        and talented <a href="https://www.erinraffertyviola.com">Erin Rafferty</a>
        that focuses on integrating live performance with electronic components.</p>
    </li>
    <li>
      <h3><%= link_to "Dictionary of Musical Invective", "https://musicalinvective.wordpress.com/" %></h3>
      <p>Wherein I discuss the state of contemporary art music.  Snarky attitude; serious thoughts.</p>
    </li>
    <li>
      <h3><%= link_to "Works", works_path %></h3>
      <p>A few representative pieces with recordings.</p>
    </li>
  </ul>

app/views/static_pages/software.html.erb
<% provide(:title, 'Software') %>
<h1>Software</h1>

<p>
  I'm a self-taught developer. I work mostly in Rails, but I prefer pure Ruby -
  I'm wary of too much scaffolding and black-box functionality,
  and I like to know what's under the hood.
</p>
<p>
  Over a year of <a href="http://www.github.com/smoip">consistent, iterative work</a>
  on my own projects demonstrates my commitment, dedication, and ability to learn.
</p>
<p>
  I love Ruby for its simplicity and elegance, but I'm a quick study and never
  pass up an opportunity to learn another useful tool.  I use Git for
  version control, and I test with rspec.
</p>
<p>
  I prefer backend to frontend design, but
  I'm competent working with bootstrap and SASS as well as custom CSS.
  I'm comfortable working with both SQLite and PostgreSQL, though I wouldn't claim
  to be an expert in the latter.
</p>
<p>
  I write code that matches and enhances my other passions: music, sound design, and brewing, and
  I consider my experience working with a broad range of people and ideas outside of
  the tech industry to be an advantage. I'm very comfortable working in a collaborative environment,
  and I'm always up to try a new approach.
</p>
<p>
  In my capacity as a composer, I have worked extensively
  with <%= link_to "Kyma", "http://kyma.symbolicsound.com/" %>,
  a sound computation engine that runs on a Small Talk-derived language, and the visual language
  <%= link_to "Max/MSP/Jitter", "http://cycling74.com/" %>.
  Working with both to create software for my own performances has given me the unique perspective of being
  simultaneously designer and end user.
</p>
<p>
  I love solving problems and never tire of tinkering.
  Here are a few of my recent and ongoing projects.
</p>
<h2>Selected Projects</h2>
<ul>
  <li>
    <h3><a href="http://www.wamibrew.com">Wamibrew</a></h3>
    <p>
      Wamibrew (<em>W</em>hat <em>Am</em> <em>I</em> <em>Brew</em>ing?) is a Rails-based algorithmic beer recipe generator for homebrewers.
      It randomly generates a real, brew-able all-grain beer recipe (based on some general rules and probabilities)
      and then attempts to heuristically determine the closest recognized style of the generated recipe based
      calculated attributes.  Every recipe guaranteed to make booze!
      <%= link_to "(github)", "http://github.com/smoip/wamibrew/" %>
    </p>
  </li>
  <li>
    <h3>Chord Wrangler</h3>
    <p>
      (In progress) A Ruby tool for computer assisted composition.  It accepts an input chord (or generates a random one)
      and then runs it through a series of successive contrapuntal transformations.  The resulting chordal
      structure can then be the basis of a piece of written-out music.
      <%= link_to "(github)", "http://github.com/smoip/chord_wrangler" %>
    </p>
  </li>
  <li>
    <h3>Maker Search</h3>
    <p>
      (In progress) Rails-based searchable archive of instrument makers and their histories aimed at young classical
      music professionals purchasing their first fine stringed instrument.
    </p>
  </li>
  <li>
    <h3>Adventure</h3>
    <p>
      My homage to the text-based adventure game genre of yore, and my first real project in ruby.
      Included here mostly as a reference point for how much I have learned since then, but it might
      also be fun if you don't mind a clunky interface and losing repeatedly.  Be sure to download
      the stable release.
      <%= link_to "(github)", "http://github.com/smoip/adventure" %>
    </p>
  </li>
</ul>

app/views/static_pages/works.html.erb
<% provide(:title, 'Works') %>
<h1>Selected Works</h1>
<div id="works-list">
  <h2>Electronics</h2>
  <table>
    <tr>
      <td>Cloud Music, electronics (Kyma), 2013.</td>
      <td><iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/213527795&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe></td>
    </tr>
    <tr>
      <td>Mode 7, electronics (Kyma), 2015.</td>
      <td><iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/198960984&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe></td>
    </tr>
  </table>
  <h2>Chamber</h2>
  <table>
    <tr>
      <td>String Quartet No. 2 - III. Mercurial, 2vn, va, vc, 2008.</td>
      <td><iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/198964002&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe></td>
     </tr>
     <tr>
      <td>Piano Quintet - II. Scherzo, pno, 2vn, va, vc, 2009.</td>
      <td><iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/213528521&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe></td>
    </tr>
    <tr>
      <td>Four Miniatures After K.V. - II. Boku Maru, cl, hn, 2perc, pno, vn, vc, 2010.</td>
      <td><iframe width="100%" height="70%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/213524850&amp;default_height=50&amp;color=e33f16&amp;theme_color=ffb624&amp;auto_play=false&amp;hide_related=true&amp;show_comments=false&amp;show_user=false&amp;show_play_account=false&amp;show_reposts=false&amp;single_active=true"></iframe></td>
    </tr>
  </table>
</div>